import 'package:flutter/material.dart';

final List<Map<String, dynamic>> dummyData = [
  {
    'title': 'Reinhold Crona',
    'smallPic': 'assets/DonorScreen/Arabic.svg',
    'subtitle': 'as-Sinbillawayn',
    'views': '120',
    'user': 'Free',
    'blood': 'AB',
    'icon': 'assets/DonorScreen/Drop_Filled.svg',
    'image': 'assets/DonorScreen/profile5.jpeg',
    'distance' : 'assets/DonorScreen/distance.svg',
    'km' : '725 km',
  },
  {
    'title': 'Mina Kulas',
    'smallPic': 'assets/DonorScreen/Arabic.svg',
    'subtitle': 'as-Sinbillawayn',
    'views': '120',
    'user': 'Free',
    'blood': 'A+',
    'icon': 'assets/DonorScreen/Drop_Filled.svg',
    'image': 'assets/DonorScreen/profile2.jpeg',
    'distance' : 'assets/DonorScreen/distance.svg',
    'km' : '345 km',
  },
  {
    'title': 'Pietro Shields Jr.',
    'smallPic': 'assets/DonorScreen/Arabic.svg',
    'subtitle': 'Sas-Sinbillawayn',
    'views': '120',
    'user': 'Free',
    'blood': 'AB',
    'icon': 'assets/DonorScreen/Drop_Filled.svg',
    'image': 'assets/DonorScreen/profile3.jpeg',
    'distance' : 'assets/DonorScreen/distance.svg',
    'km' : '431 km',
  },
  {
    'title': 'Dulce Parker',
    'smallPic': 'assets/DonorScreen/Arabic.svg',
    'subtitle': 'Sas-Sinbillawayn',
    'views': '120',
    'user': 'Free',
    'blood': 'B+',
    'icon': 'assets/DonorScreen/Drop_Filled.svg',
    'image': 'assets/DonorScreen/profile4.jpeg',
    'distance' : 'assets/DonorScreen/distance.svg',
    'km' : '825 km',
  },
  {
    'title': 'Katelynn Schulist',
    'smallPic': 'assets/DonorScreen/Arabic.svg',
    'subtitle': 'Sas-Sinbillawayn',
    'views': '120',
    'user': 'Free',
    'blood': 'A-',
    'icon': 'assets/DonorScreen/Drop_Filled.svg',
    'image': 'assets/DonorScreen/profile5.jpeg',
    'distance' : 'assets/DonorScreen/distance.svg',
    'km' : '25 km',
  },
  {
    'title': 'Kory Pouros',
    'smallPic': 'assets/DonorScreen/Arabic.svg',
    'subtitle': 'Sas-Sinbillawayn',
    'views': '120',
    'user': 'Free',
    'blood': 'B-',
    'icon': 'assets/DonorScreen/Drop_Filled.svg',
    'image': 'assets/DonorScreen/profile6.jpeg',
    'distance' : 'assets/DonorScreen/distance.svg',
    'km' : '72 km',
  },
  {
    'title': 'Dorris Kassulke',
    'smallPic': 'assets/DonorScreen/Arabic.svg',
    'subtitle': 'Sas-Sinbillawayn',
    'views': '120',
    'user': 'Free',
    'blood': 'O+',
    'icon': 'assets/DonorScreen/Drop_Filled.svg',
    'image': 'assets/DonorScreen/profile7.jpeg',
    'distance' : 'assets/DonorScreen/distance.svg',
    'km' : '57 km',
  },
  {
    'title': 'Eldora Kihn',
    'smallPic': 'assets/DonorScreen/Arabic.svg',
    'subtitle': 'Sas-Sinbillawayn',
    'views': '120',
    'user': 'Free',
    'blood': 'O-',
    'icon': 'assets/DonorScreen/Drop_Filled.svg',
    'image': 'assets/DonorScreen/profile8.jpeg',
    'distance' : 'assets/DonorScreen/distance.svg',
    'km' : '769 km',
  },
  // Add more items as needed
];